services:
  # 1. Služba pro PostgreSQL
  postgres:
    image: postgres:16-alpine # Používáme stabilní PostgreSQL
    restart: always
    environment:
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: password
      POSTGRES_DB: symfony_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data # Ukládáme data DB

  # 2. Služba pro PHP-FPM (Symfony)
  php:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www/html/app
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/html:delegated # Připojujeme aktuální složku do kontejneru
    depends_on:
      - postgres
    environment:
      - COMPOSER_MEMORY_LIMIT=-1  # Odstraňuje limit pro Composer
      - PHP_MEMORY_LIMIT=2048M    # Zvyšuje limit PHP

  # 3. Služba pro Webový server (Nginx)
  nginx:
    image: nginx:stable-alpine
    restart: always
    ports:
      - "80:80" # Váš projekt bude dostupný na http://localhost:80
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf # Konfigurace Nginx
    depends_on:
      - php # Nginx by neměl startovat dříve než PHP

  # 4. Služba pro frontend (Node.js)
  node:
    image: node:22-alpine # Používáme oficiální LTS obraz Node.js na Alpine
    working_dir: /var/www/html/app # Pracovní adresář uvnitř kontejneru, kde je aplikace Symfony
    volumes:
      - .:/var/www/html:delegated # Připojujeme celou složku projektu, aby Node.js mohl vidět assets/ a zapisovat do public/build

  # 5. Elasticsearch (Search Engine)
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  # 6. Kibana (Visualization)
  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.3
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch

  # 7. KeyDB (Redis alternative)
  keydb:
    image: eqalpha/keydb:latest
    command: ["keydb-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - keydb-data:/data

volumes:
  db-data:
  elasticsearch-data:
  keydb-data:

