services:
  # 1. Сервис для PostgreSQL
  postgres:
    image: postgres:16-alpine # Используем стабильный PostgreSQL
    restart: always
    environment:
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: password
      POSTGRES_DB: symfony_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data # Сохраняем данные БД

  # 2. Сервис для PHP-FPM (Symfony)
  php:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www/html/app
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/html:delegated # Монтируем текущую папку в контейнер
    depends_on:
      - postgres

  # 3. Сервис для Веб-сервера (Nginx)
  nginx:
    image: nginx:stable-alpine
    restart: always
    ports:
      - "80:80" # Ваш проект будет доступен по http://localhost:80
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf # Конфигурация Nginx
    depends_on:
      - php # Nginx не должен стартовать раньше PHP

  # 4. Сервис для сборки фронтенда (Node.js)
  node:
    image: node:22-alpine # Используем официальный образ Node.js LTS на Alpine
    working_dir: /var/www/html/app # Рабочая директория внутри контейнера, где находится Symfony-приложение
    volumes:
      - .:/var/www/html:delegated # Монтируем всю папку проекта, чтобы Node.js мог видеть assets/ и записывать в public/build

volumes:
  db-data:

