# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.supported_locales: 'cs|en|ru'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $emailDelay: '%env(int:EMAIL_SEQUENCE_DELAY)%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # Konfigurace továrny pro výběr implementace odesílače e-mailů (SMTP vs Soubor)
    App\Service\EmailSenderInterface:
        factory: ['@App\Service\Factory\EmailSenderFactory', 'create']
        arguments: ['%env(string:EMAIL_DELIVERY_MODE)%']

    App\Service\EmailService:
        arguments:
            $senderEmail: '%env(MAILER_SENDER_EMAIL)%'
            $senderName: '%env(MAILER_SENDER_NAME)%'

    App\Service\FileEmailService:
        arguments:
            $senderEmail: '%env(MAILER_SENDER_EMAIL)%'
            $senderName: '%env(MAILER_SENDER_NAME)%'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones