twig:
    file_name_pattern: '*.twig'
    paths:
        '%kernel.project_dir%/templates': ~
        '%kernel.project_dir%/templates/index': 'Index'
        '%kernel.project_dir%/templates/greeting': 'Greeting'

when@test:
    twig:
        strict_variables: true
